import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMediumSquare,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import { useState } from "react";
import todo from "../public/todo.png";
import weather from "../public/weather.png";
import mobile from "../public/mobile.png";
import flutter from "../public/flutter.png"
import image from "../public/image.png";
import reactNative from "../public/home_hero.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ragul</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.10.1/devicon.min.css"
        ></link>

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"
        />
      </Head>
      <main className="px-10 bg-white lg:px-20 dark:bg-gray-900">
        <nav className="flex justify-between py-10 mb-12">
          <h1 className="text-4xl font-burtons dark:text-white">Ragul</h1>
          <ul className="flex justify-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="text-2xl cursor-pointer dark:text-white"
              />
            </li>
            <li>
              <a
                href="/Rasalingam Ragul.pdf"
                download="Ragul_Rasalingam.pdf"
                className="px-4 py-2 ml-8 text-white rounded-md bg-gradient-to-r from-cyan-500 to-cyan-600"
              >
                CV
              </a>
            </li>
          </ul>
        </nav>

        <div className="px-10 mt-0 text-center">
          <h2 className="text-5xl font-medium text-teal-600">
            Rasalingam Ragul
          </h2>
          <h3 className="py-2 text-2xl dark:text-white">
            Developer and designer{" "}
          </h3>
        </div>
        <div className="flex justify-center gap-16 text-5xl text-gray-600">
          <a href="https://www.linkedin.com/in/rasalingam-ragul/">
            <AiFillLinkedin className="hover:scale-125" />
          </a>
          <a href="https://github.com/rragul">
            <AiFillGithub className="hover:scale-125" />
          </a>
          <a href="https://medium.com/@r-ragul">
            <AiFillMediumSquare className="hover:scale-125" />
          </a>
        </div>
        <div className="relative mx-auto mt-20 overflow-hidden rounded-full bg-gradient-to-b from-teal-600 w-80 h-80">
          <Image src={deved} alt="img" layout="fill" objectFit="cover" />
        </div>

        <section>
        <h3 className="mt-6 mb-6 mr-10 text-4xl font-bold text-center font-burtons dark:text-white">
               My Skills
              </h3>
          <div className="flex justify-center">
            <section className="flex mt-4 space-x-20">
              <i className="mr-3 text-6xl devicon-java-plain colored"></i>
              <i className="mr-3 text-6xl devicon-python-plain colored"></i>
              <i className="mr-3 text-6xl devicon-javascript-plain colored"></i>
              
              <i className="mr-3 text-6xl devicon-kotlin-plain-wordmark colored"></i>
              <i className="mr-3 text-6xl devicon-c-plain colored"></i>
              <i className="mr-3 text-6xl devicon-html5-plain-wordmark colored"></i>
              <i className="mr-3 text-6xl devicon-css3-plain-wordmark colored"></i>
            </section>
          </div>
          <div className="flex justify-center">
            <section className="flex mt-4 space-x-20">
              <i className="mr-3 text-6xl devicon-react-original-wordmark colored"></i>
              <i className="mr-3 text-6xl devicon-nodejs-plain-wordmark colored"></i>
              <i className="mr-3 text-6xl devicon-tailwindcss-original-wordmark colored"></i>
              <i className="mr-3 text-6xl devicon-flutter-plain colored"></i>
              <i class="devicon-androidstudio-plain-wordmark colored text-6xl mr-3"></i>
            </section>
          </div>
        </section>

        <section>
          <div>
            <h3 className="mb-6 text-4xl font-bold text-center mt-14 font-burtons dark:text-white">
              My Works
            </h3>
            <section className="grid grid-cols-3 py-4">
              {/* e-shop */}
              <div className="max-w-sm mx-4 overflow-hidden bg-gray-300 rounded shadow-lg dark:bg-gray-400">
                <Image
                  src={flutter}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="mb-1 text-xl font-bold">E-Shop App</div>
                  <p className="mb-2 text-m">Using Flutter And Firebase</p>
                  <section className="flex">
                  
                  <a
                    className="px-3 py-1 text-white bg-teal-600 rounded"
                    href="https://github.com/rragul/our_shops"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="mr-1 devicon-flutter-plain text-m"></i>
                    Source
                  </a>
                  </section>
                </div>
              </div>
              {/* weather app */}
              <div className="max-w-sm mx-4 overflow-hidden bg-gray-300 rounded shadow-lg dark:bg-gray-400">
                <Image
                  src={weather}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="mb-1 text-xl font-bold">weather App</div>
                  <p className="mb-2 text-m">Using React and Axios</p>
                  <section className="flex">
                  <a
                    className="px-3 py-1 mr-5 text-white bg-teal-600 rounded"
                    href="https://rragul.github.io/weather-app/"
                    target="_blank" rel="noreferrer">
                    View
                  </a>
                  <a
                    className="px-3 py-1 text-white bg-teal-600 rounded"
                    href="https://github.com/rragul/weather-app"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="mr-1 devicon-react-original text-m"></i>
                    Source
                  </a>
                  </section>
                </div>
              </div>
              {/* React native */}
              <div className="max-w-sm mx-4 overflow-hidden bg-gray-300 rounded shadow-lg dark:bg-gray-400">
                <Image
                  src={reactNative}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="mb-1 text-xl font-bold">ProNef</div>
                  <p className="mb-2 text-m">Using React Native</p>
                  <section className="flex">
                  <a
                    className="px-3 py-1 mr-5 text-white bg-teal-600 rounded"
                    href="https://curly-shadow-6721.on.fleek.co/"
                    target="_blank" rel="noreferrer">
                    View
                  </a>
                  <a
                    className="px-3 py-1 text-white bg-teal-600 rounded"
                    href="https://github.com/rragul/react-native-app"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="mr-1 devicon-react-plain text-m"></i>
                    Source
                  </a>
                  </section>
                </div>
              </div>
              {/* mobile store */}
              <div className="max-w-sm mx-4 overflow-hidden bg-gray-300 rounded shadow-lg dark:bg-gray-400">
                <Image
                  src={mobile}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="mb-1 text-xl font-bold">
                    Mobile Store
                  </div>
                  <p className="mb-2 text-m">Using React, Node and MongoDB </p>
                  <section className="flex">
                    <a
                      className="px-3 py-1 mr-4 text-white bg-teal-600 rounded"
                      href="https://mobile-store-dwn8.onrender.com/"
                      target="_blank" rel="noreferrer">
                      View
                    </a>
                    <a
                      className="px-3 py-1 mr-3 text-white bg-teal-600 rounded"
                      href="https://github.com/rragul/mobile-store"
                      target="_blank" rel="noreferrer"
                    >
                      <i className="mr-1 devicon-react-original text-m"></i>
                      Source
                    </a>
                    <a
                      className="px-3 py-1 text-white bg-teal-600 rounded"
                      href="https://github.com/rragul/mongo-connect"
                      target="_blank" rel="noreferrer"
                    >
                      <i className="mr-1 devicon-nodejs-plain text-m"></i>
                      Source
                    </a>
                  </section>
                </div>
              </div>
              {/* image generator */}
               <div className="max-w-sm mx-4 my-4 overflow-hidden bg-gray-300 rounded shadow-lg dark:bg-gray-400">
                <Image
                  src={image}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="mb-1 text-xl font-bold">Image Generator</div>
                  <p className="mb-2 text-m">Using React, Node and OpenAI</p>
                  <section className="flex">
                 
                  <a
                    className="px-3 py-1 text-white bg-teal-600 rounded"
                    href="https://github.com/rragul/image_genarator_frontend"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="mr-1 devicon-react-original text-m"></i>
                    Source
                  </a>
                  <a
                    className="px-3 py-1 mx-4 text-white bg-teal-600 rounded"
                    href="https://github.com/rragul/Image_Genaretor_backend"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="mr-1 devicon-nodejs-plain text-m"></i>
                    Source
                  </a>
                  </section>
                </div>
              </div>
              {/* Todo */}
              <div className="max-w-sm mx-4 my-4 overflow-hidden bg-gray-300 rounded shadow-lg dark:bg-gray-400">
                <Image
                  src={todo}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="mb-1 text-xl font-bold">Todo App</div>
                  <p className="mb-2 text-m">Using React</p>
                  <section className="flex">
                  <a className="px-3 py-1 mr-5 text-white bg-teal-600 rounded"
                    href="https://rragul.github.io/Todo-App/"
                    target="_blank" rel="noreferrer"
                  >
                    View
                  </a>
                  <a
                    className="px-3 py-1 text-white bg-teal-600 rounded"
                    href="https://github.com/rragul/Todo-App"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="mr-1 devicon-react-original text-m"></i>
                    Source
                  </a>
                  </section>
                </div>
              </div>
            </section>
          </div>
        </section>
      </main>
    </div>
  );
}
