import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMediumSquare,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import { useState } from "react";
import todo from "../public/todo.png";
import weather from "../public/weather.png";
import mobile from "../public/mobile.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ragul</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.10.1/devicon.min.css"
        ></link>

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"
        />
      </Head>
      <main className="bg-white px-10 lg:px-20 dark:bg-gray-900">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-4xl font-burtons dark:text-white">Ragul</h1>
          <ul className="flex justify-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl dark:text-white"
              />
            </li>
            <li>
              <a
                href="/Ragul_Rasalingam.pdf"
                download="Ragul_Rasalingam.pdf"
                className=" bg-gradient-to-r from-cyan-500 to-cyan-600  text-white px-4 py-2 rounded-md ml-8"
              >
                CV
              </a>
            </li>
          </ul>
        </nav>

        <div className="text-center px-10 mt-0">
          <h2 className="text-5xl text-teal-600 font-medium">
            Rasalingam Ragul
          </h2>
          <h3 className="text-2xl py-2 dark:text-white">
            Developer and designer{" "}
          </h3>
        </div>
        <div className="flex justify-center gap-16 text-5xl text-gray-600">
          <a href="https://www.linkedin.com/in/rasalingam-ragul/">
            <AiFillLinkedin className="hover:scale-125" />
          </a>
          <a href="https://github.com/rragul">
            <AiFillGithub className="hover:scale-125" />
          </a>
          <a href="https://medium.com/@r-ragul">
            <AiFillMediumSquare className="hover:scale-125" />
          </a>
        </div>
        <div className="relative mx-auto bg-gradient-to-b from-teal-600 rounded-full w-80 h-80 mt-20 overflow-hidden">
          <Image src={deved} alt="img" layout="fill" objectFit="cover" />
        </div>

        <section>
        <h3 className="text-4xl text-center mt-6 mb-6 mr-10 font-bold font-burtons dark:text-white">
               My Skills
              </h3>
          <div className="flex justify-center">
            <section className="flex space-x-20 mt-4">
              <i className="devicon-java-plain colored text-6xl mr-3"></i>
              <i className="devicon-python-plain colored text-6xl mr-3"></i>
              <i className="devicon-javascript-plain colored text-6xl mr-3"></i>
              
              <i className="devicon-kotlin-plain-wordmark colored text-6xl mr-3"></i>
              <i className="devicon-c-plain colored text-6xl mr-3"></i>
              <i className="devicon-html5-plain-wordmark colored text-6xl mr-3"></i>
              <i className="devicon-css3-plain-wordmark colored text-6xl mr-3"></i>
            </section>
          </div>
          <div className="flex justify-center">
            <section className="flex space-x-20 mt-4">
              <i className="devicon-react-original-wordmark colored text-6xl mr-3"></i>
              <i className="devicon-nodejs-plain-wordmark colored text-6xl mr-3"></i>
              <i className="devicon-tailwindcss-original-wordmark colored text-6xl mr-3"></i>
              <i className="devicon-flutter-plain colored text-6xl mr-3"></i>
              <i class="devicon-androidstudio-plain-wordmark colored text-6xl mr-3"></i>
            </section>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-4xl text-center mt-14 mb-6 font-bold font-burtons dark:text-white">
              My Works
            </h3>
            <section className="flex justify-evenly py-4">
              <div className=" max-w-sm rounded overflow-hidden shadow-lg bg-gray-300 dark:bg-gray-400">
                <Image
                  src={todo}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="font-bold text-xl mb-1">Todo App</div>
                  <p className="text-m mb-2">Using React</p>
                  <section className="flex">
                  <a className="bg-teal-600 text-white px-3 py-1 rounded mr-5"
                    href="https://rragul.github.io/Todo-App/"
                    target="_blank" rel="noreferrer"
                  >
                    View
                  </a>
                  <a
                    className="bg-teal-600 text-white px-3 py-1 rounded"
                    href="https://github.com/rragul/Todo-App"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="devicon-react-original text-m mr-1"></i>
                    Source
                  </a>
                  </section>
                </div>
              </div>
              <div className=" max-w-sm rounded overflow-hidden shadow-lg bg-gray-300 dark:bg-gray-400">
                <Image
                  src={weather}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="font-bold text-xl mb-1">weather App</div>
                  <p className="text-m mb-2">Using React and Axios</p>
                  <section className="flex">
                  <a
                    className="bg-teal-600 text-white px-3 py-1 rounded mr-5"
                    href="https://rragul.github.io/weather-app/"
                    target="_blank" rel="noreferrer">
                    View
                  </a>
                  <a
                    className="bg-teal-600 text-white px-3 py-1 rounded"
                    href="https://github.com/rragul/weather-app"
                    target="_blank" rel="noreferrer"
                  >
                    <i className="devicon-react-original text-m mr-1"></i>
                    Source
                  </a>
                  </section>
                </div>
              </div>
              <div className=" max-w-sm rounded overflow-hidden shadow-lg bg-gray-300 dark:bg-gray-400">
                <Image
                  src={mobile}
                  alt="img"
                  className="w-full"
                  objectFit="cover"
                />
                <div className="px-6 py-2">
                  <div className="font-bold text-xl mb-1">
                    Mobile Store
                  </div>
                  <p className="text-m mb-2">Using React, Node and MongoDB </p>
                  <section className="flex">
                    <a
                      className="bg-teal-600 text-white px-3 py-1 rounded mr-5"
                      href="https://mobile-store-dwn8.onrender.com/"
                      target="_blank" rel="noreferrer">
                      View
                    </a>
                    <a
                      className="bg-teal-600 text-white px-3 py-1 rounded mr-5"
                      href="https://github.com/rragul/mobile-store"
                      target="_blank" rel="noreferrer"
                    >
                      <i className="devicon-react-original text-m mr-1"></i>
                      Source
                    </a>
                    <a
                      className="bg-teal-600 text-white px-3 py-1 rounded"
                      href="https://github.com/rragul/mongo-connect"
                      target="_blank" rel="noreferrer"
                    >
                      <i className="devicon-nodejs-plain text-m mr-1"></i>
                      Source
                    </a>
                  </section>
                </div>
              </div>
            </section>
          </div>
        </section>
      </main>
    </div>
  );
}
